### ISSUE TITLE
ui.json file missing

### ISSUE THREAD

**Issue by foxhoundv** [ALLTERCO/fleet-management#11]
Just loaded a fresh copy and this is the error message:
```
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/backend/cfg/registry/ui.json'
} Promise {
  <rejected> Error: ENOENT: no such file or directory, open '/app/backend/cfg/registry/ui.json'
      at async open (node:internal/fs/promises:639:25)
      at async Object.writeFile (node:internal/fs/promises:1216:14)
      at async saveRegistry (/app/backend/dist/modules/Registry.js:63:12)
      at async addToRegistry (/app/backend/dist/modules/Registry.js:68:12)
      at async ensureDefaultDashboards (/app/backend/dist/modules/Registry.js:95:9)
      at async Object.ensureDefaults (/app/backend/dist/modules/Registry.js:104:5)
      at async main (/app/backend/dist/app.js:127:5) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/app/backend/cfg/registry/ui.json'
  }
}

``` 

EDIT: Actually there are other files that are missing as well... this is just one.

**Comment by zetxx** [comment]
Hey there,
know issue.
just submitted a patch for it.

**Comment by sahil-devinci** [comment]
> Hey there, know issue. just submitted a patch for it.

Thanks for the update. Do you know by will the patch merge to master

**Comment by sahil-devinci** [comment]
Using docker method 
It has issues with postgres root user

**Comment by zetxx** [comment]
> Using docker method It has issues with postgres root user

please open another issue

**Comment by zetxx** [comment]
> Thanks for the update. Do you know by will the patch merge to master
basically, you want to create few folders in this volume: `fm-backend-cfg-v`

how to find volume path: `docker volume inspect fm-backend-cfg-v`, you should look for `       "Mountpoint": ".....some path....`
in the volume folder you should create 3 dirs: `'node-red', 'components', 'registry'`
thats all (don't forget to restart the container)

**Comment by sahil-devinci** [comment]
@zetxx I have added the folder still it does not work

**Comment by zetxx** [comment]
can you attach to fm container and run `ls -la /app/backend/cfg/` then paste the output

**Comment by foxhoundv** [comment]
I have done the same thing above and it doesn't work either.
When I try to attach to the fm container it says that it is trying to restart and to wait until it is running. However I have manually restarted and and it does the same thing.
![image](https://github.com/user-attachments/assets/2f88a68c-45ec-4111-9bd4-7ea09b6f2b14)

**Comment by foxhoundv** [comment]
Nevermind it works now. The issue was that the only way to access the folder directory was to "sudo -i" and then when I created those folders they were under "root:root" ownership. Once I changed that and everything recursively, it worked.

**Comment by zetxx** [comment]
this should be fixed in the next release :)
