### ISSUE TITLE
mDNS won't stay enabled

### ISSUE THREAD

**Issue by foxhoundv** [ALLTERCO/fleet-management#12]
When I try to discover devices it says I need to enable mDNS in settings...
![image](https://github.com/user-attachments/assets/12041b18-cb29-423a-b71d-ad7e6d13dc43)

I do that...
![image](https://github.com/user-attachments/assets/2ef0037d-e056-4a7a-b90c-4ab65814d27b)

It says it saved it but when I go to discover devices again...
![image](https://github.com/user-attachments/assets/0cedd170-d764-4373-9e99-c0b5e6bdfe52)

It says I need to enable the mDNS, and it never stays enabled. I refresh the page after enabling it and it won't enable.

**Comment by foxhoundv** [comment]
Please be advised that now my app version is...
![image](https://github.com/user-attachments/assets/cb022fb8-3535-43bf-a83c-4ac0e303eca0)

and it still doesn't work.

**Comment by foxhoundv** [comment]
Everytime I save settings, the last error keeps happening. Also the runtime.lastError count keeps going up.
![Screenshot 2024-09-03 162432](https://github.com/user-attachments/assets/298147be-26b9-4c42-9d9d-713a254d9b09)

**Comment by zetxx** [comment]
https://github.com/ALLTERCO/fleet-management/blob/main/README.md
"mdns packet repeater (mdns-repeater) - this will get mdns packet from* interface and will redirect it to* interface"

**Comment by zetxx** [comment]
if you look in the docker-compose file:
`
https://github.com/ALLTERCO/fleet-management/blob/main/docker-compose.yml#L83
`

you will see thant you need to define env vars for "from" iface to "to" iface

**Comment by foxhoundv** [comment]
When you say "interface" do you mean port? If so, is there a specific port I should use that is common for mDNS traffic. Sorry, the README isn't that helpful.

**Comment by zetxx** [comment]
nope.(all of the following examples uses example name `fleet-net`)
run: `docker network ls`, and output should look similar to:
```bash
docker network ls                                                                                                                                                                    1 
NETWORK ID     NAME                   DRIVER    SCOPE
b6c33e04a65f   bridge                 bridge    local
11ca1ad57df5   mysql_default          bridge    local
c5ed3064257d   none                   null      local
b38afdac9e91   fleet-net_default   bridge    local
```

you should look for network that have in it is name `fleet-net`

after that you should run `docker network inspect fleet-net_default`
output:

```json
[
    {
        "Name": "fleet-net_default",
        "Id": "b38afdac9e91492a2b4a4f5cffb7042bdb2b53106dfbc285bf0d4fb94f738542",
        "Created": "2024-08-05T15:02:06.971255439+03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "web-services",
            "com.docker.compose.version": "2.29.1"
        }
    }
]

```
this is `"Subnet": "172.19.0.0/16"` what you are interested in.
this is your network address.
after that we should find correct interfaces.
you should run `ip a`, it will give you short details for every network.

```bash
: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 7c:4d:8f:a2:13:a5 brd ff:ff:ff:ff:ff:ff
    inet ******/24 brd 10.99.99.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet 1.2.3.4/22 brd 192.168.207.255 scope global dynamic noprefixroute enp1s0
       valid_lft 1231sec preferred_lft 1231sec
    inet6 fd32:7100:c2ba:b3f5:15b7:4228:9883:7cdd/64 scope global dynamic noprefixroute 
       valid_lft 1736sec preferred_lft 1736sec
    inet6 fe80::ec3a:7bb3:e787:c021/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
8: br-11ca1ad57df5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:b2:1a:b1:97 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 brd 172.20.255.255 scope global br-11ca1ad57df5
       valid_lft forever preferred_lft forever
    inet6 fe80::42:b2ff:fe1a:b197/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
9: br-39e053079bd1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c6:1c:ef:4f brd ff:ff:ff:ff:ff:ff
    inet 172.23.1.1/24 brd 172.23.1.255 scope global br-39e053079bd1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c6ff:fe1c:ef4f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
10: br-9f22f2f0e331: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ff:be:b2:5c brd ff:ff:ff:ff:ff:ff
    inet 172.23.0.1/24 brd 172.23.0.255 scope global br-9f22f2f0e331
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ffff:febe:b25c/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
11: br-b38afdac9e91: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:7a:26:e0:17 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-b38afdac9e91
       valid_lft forever preferred_lft forever
12: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:1c:e2:72:6d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
13: br-0d577568934b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:8f:24:00:09 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-0d577568934b
       valid_lft forever preferred_lft forever
15: vethed75c83@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether 6e:24:82:e0:5f:ed brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::6c24:82ff:fee0:5fed/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
17: veth443a3c8@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-9f22f2f0e331 state UP group default 
    link/ether a2:3f:16:91:00:ed brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::a03f:16ff:fe91:ed/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
19: vethabf7afa@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether 6a:0c:e2:1b:f5:12 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::680c:e2ff:fe1b:f512/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
21: vethcdd1ee1@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-11ca1ad57df5 state UP group default 
    link/ether 6e:28:fd:a0:1c:7c brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::6c28:fdff:fea0:1c7c/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
23: veth78b436c@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether 9a:84:7e:64:db:77 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::9884:7eff:fe64:db77/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
25: veth844e25c@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether 92:b8:a4:6d:30:62 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::90b8:a4ff:fe6d:3062/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
27: veth81b027a@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether a2:da:60:0f:d9:27 brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::a0da:60ff:fe0f:d927/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
29: veth01eed25@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-39e053079bd1 state UP group default 
    link/ether 6e:12:22:7f:08:22 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::6c12:22ff:fe7f:822/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

my primary network is: `enp1s0`
we should listen on this iface
and fleet manager iface is `br-b38afdac9e91` because ip network matches
so you should put in your env var

```bash
export MDNS_ON=enp1s0
export MDNS_TO=br-b38afdac9e91
```

**Comment by foxhoundv** [comment]
These instructions are really great, but I have to run "docker compose down", edit the YAML file, and when I run "docker copose up -d" the interface TO changes.

**Comment by foxhoundv** [comment]
So I created a different host folder for a "fleet-mdns" and pulled the mdns-repeater out of the original docker-compose.yml file and created a new docker-compose.yml under the fleet-mdns folder. This way I could start the original fleet-management stack and then after getting the interface information, add it to the other docker-compose.yml file and start it. Everything seems to communicate fine except there are some errors.
![image](https://github.com/user-attachments/assets/19b4a88c-7974-41fc-9fdf-2d10906c2ab4)
It is finding devices on the network (I just didn't post the info because of too much personal info) but it keeps failing to "assert".

**Comment by foxhoundv** [comment]
This is now what I get from the fleet-manager logs when I try to enable the mdns from settings:
![image](https://github.com/user-attachments/assets/8339f435-7625-4084-bca4-77c5c41bfbe4)

**Comment by zetxx** [comment]
> So I created a different host folder for a "fleet-mdns" and pulled the mdns-repeater out of the original docker-compose.yml file and created a new docker-compose.yml under the fleet-mdns folder. This way I could start the original fleet-management stack and then after getting the interface information, add it to the other docker-compose.yml file and start it. Everything seems to communicate fine except there are some errors. ![image](https://private-user-images.githubusercontent.com/16512250/366160872-19b4a88c-7974-41fc-9fdf-2d10906c2ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzY5OTgsIm5iZiI6MTcyNjAzNjY5OCwicGF0aCI6Ii8xNjUxMjI1MC8zNjYxNjA4NzItMTliNGE4OGMtNzk3NC00MWZjLTlmZGYtMmQxMDkwNmMyYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZTVkNDRmYjJhZDAwYzA1NmRjNzY2N2VkZDkzZTllZWY3ZmUyZjM3NDRmYzg5NGJlMTdmMTM0ZGY0ZWNiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CPdDm6aMwM1X2tJRTaH2kGhKYTx7_6LEbViO6uH5Xow) It is finding devices on the network (I just didn't post the info because of too much personal info) but it keeps failing to "assert".

it is normal, those devices are probably some ios devices, or some other devices that are not shelly devices :) ... keep in mind that many devices uses mdns for discovery.

**Comment by zetxx** [comment]
live it for a while and see discovered tab

**Comment by zetxx** [comment]
you dont need to move in new `docker-compose`, you need only .env file that sets `mdns_on` and `mdns_to` vars
as stated here https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

**Comment by foxhoundv** [comment]
I feel like I am missing something... I reset my docker-compose.yml file back to what it was with mDNS in there. I created a .env file and declared it like stated from the docker website: 

```typescript
   mdns-repeater:
    image: shellygroup/mdns-repeater:latest
    environment:
      LISTEN_ON: ${MDNS_ON}
      REPEAT_TO: ${MDNS_TO}
    container_name: mdns-repeater
    restart: unless-stopped
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
    env_file: ".env"
```

Now, since I ran `docker compose up -d` the variables changed, so I ran `ip a` to get them again and changed the contents of the .env file.  It won't see what I have changed now.

**Comment by foxhoundv** [comment]
Ok, I found a way to make this work. I use portainer and so I went into the mdns container... stopped it, then recreated it and changed the values this way. It seems like there should be a way for the images to pull the interface values upon startup and creation of the containers. I just am not a programmer. I guess if the way Docker works and it hides those values on purpose for security... or maybe if there was a way to have the mdns repeater work off the named networks?? I know I don't know enough about it though.

**Comment by zetxx** [comment]
> Ok, I found a way to make this work. I use portainer and so I went into the mdns container... stopped it, then recreated it and changed the values this way. It seems like there should be a way for the images to pull the interface values upon startup and creation of the containers. I just am not a programmer. I guess if the way Docker works and it hides those values on purpose for security... or maybe if there was a way to have the mdns repeater work off the named networks?? I know I don't know enough about it though.

Actyaly docker dont hide anything, it just group processes or logic by groups like network, volume, container, image.
And yes, it can be done by a script, but hey, 1 step at a time ;) .

**Comment by zetxx** [comment]
also there is a `docker compose down <container> ` or `docker rm <container> -f` ..
since you made it, im closing this issue .
