### ISSUE TITLE
Connection is not replacing

### ISSUE THREAD

**Issue by selimbayhan** [ALLTERCO/fleet-management#2]
When connection is closed on shelly device side for some reason such as power outage. Server side code does not replace the new incoming connection so the code writes duplicate values to the database.  I think there is a code for replacing new connection with the old one but it is not working.

                logger.info('There is already existing websocket connection for this device. Replacing. shellyID:[%s]', shellyID);
                found.setTransport(new WebSocketTransport(ws));
                found.status = message.params;

**Comment by zetxx** [comment]
Hi there,
since last update this snippet is no more relevant.
You can try latest version and post new issue if it still persists.
