### ISSUE TITLE
Unable to Connect Shelly Device to Fleet Management Application

### ISSUE THREAD

**Issue by philippbruhin** [ALLTERCO/fleet-management#6]
## Description: 

I am encountering difficulties connecting my Shelly device to the Fleet Management application, despite both devices being on the same network and properly configured. When attempting to configure the WebSocket (WS) URL in the Fleet Management application with the address `ws://127.0.0.1:7011/shelly`, the application still reports "No devices found."

Please check following animated GIF:

![2024-04-10_16-55-45_WS_connection](https://github.com/ALLTERCO/fleet-management/assets/7021907/f8cac19e-acb3-4dd9-b725-e1f18a5b60d5)

The WebSocket error log can be found on the left:

![image](https://github.com/ALLTERCO/fleet-management/assets/7021907/c067b29b-29e6-49bb-9ded-721909ef4eae)

## Expected Behavior:

Upon configuring the correct WebSocket URL for the Shelly device within the Fleet Management application, the application should successfully establish a connection and detect the Shelly device on the local network.

## Actual Behavior:

Despite configuring the WebSocket URL as instructed, the Fleet Management application fails to detect any devices, displaying the message "No devices found."

**Comment by taulfsime** [comment]
@philippbruhin 127.0.0.1 is an internal IP that can be resolved only within your machine, check the ip address of your pc in the router settings or wifi configuration and point the shelly ws to ws://PC_IP:7011/shelly

**Comment by zetxx** [comment]
Hi there,
since last update this snippet is no more relevant.
You can try latest version and post new issue if it still persists.

**Comment by philippbruhin** [comment]
Thank you @taulfsime and @zetxx for your appreciated feedback that did help. I am going to close this issue.
