### ISSUE TITLE
Event "Shelly.Disconnect" doesn't work

### ISSUE THREAD

**Issue by shmateyev** [ALLTERCO/fleet-management#9]
Hi, the event "Shelly.Disconnect" doesn't work.  Either backend or frontend.  We made plugin, all events are sending no problem except Disconnect.  Also, in frontend, if you disconnect some devices, they keep showing like online untill reboot the server.  Any solution?

**Comment by zetxx** [comment]
Hi there,
since last update this snippet is no more relevant.
You can try latest version and post new issue if it still persists.
